export const backgroundGray = '#f7f7f7'
export const disabledGray = '#d9d9d9'
export const blackHigh = 'rgba(0,0,0, 0.85)'
export const blackLow = 'rgba(0,0,0, 0.45)'
export const white = '#fff'
export const black = '#000'
export const primary = '#6666ff'
